/* Shared, versioned configuration contract. No customer identity is accepted here. */
(() => {
 const fields=['app_name','short_name','business_name','subtitle','logo_url','icon_url','primary_color','secondary_color','accent_color','background_color','menu_layout'];
 const layouts=['original','left','right','bottom'];
 const colorKeys=['primary_color','secondary_color','accent_color','background_color'];
 const presets={Standard:{},Blu:{primary_color:'#174a8b',secondary_color:'#dce8f7',accent_color:'#f7d977',background_color:'#f4f7fb'},Verde:{primary_color:'#26664f',secondary_color:'#b6e0cd',accent_color:'#f7d977',background_color:'#f5f3eb'},Rosso:{primary_color:'#a52c35',secondary_color:'#e4e5e7',accent_color:'#f7d977',background_color:'#faf5f3'},Arancio:{primary_color:'#98430e',secondary_color:'#ffe2ba',accent_color:'#f7d977',background_color:'#fff8ef'},Viola:{primary_color:'#683487',secondary_color:'#e5d7ef',accent_color:'#f7d977',background_color:'#f8f5fc'},Scuro:{primary_color:'#9ad9bd',secondary_color:'#293d35',accent_color:'#f7d977',background_color:'#18231e'}};
 function luminance(color){if(!/^#[0-9a-f]{6}$/i.test(color))throw Error('Colore non valido');const c=color.slice(1).match(/../g).map(x=>parseInt(x,16)/255).map(x=>x<=.04045?x/12.92:((x+.055)/1.055)**2.4);return .2126*c[0]+.7152*c[1]+.0722*c[2];}
 function contrast(a,b){const x=luminance(a),y=luminance(b);return (Math.max(x,y)+.05)/(Math.min(x,y)+.05);}
 function ink(color){return contrast(color,'#000000')>contrast(color,'#ffffff')?'#000000':'#ffffff';}
 function capabilities(raw={}){const supported=Array.isArray(raw.fields)?fields.filter(f=>raw.fields.includes(f)):[];const menus=Array.isArray(raw.menu_layouts)?layouts.filter(x=>raw.menu_layouts.includes(x)):['original'];return {version:raw.version===2?2:1,fields:supported,menu_layouts:menus.length?menus:['original'],themes:Array.isArray(raw.themes)?Object.keys(presets).filter(x=>raw.themes.includes(x)):[],defaults:raw.defaults&&typeof raw.defaults==='object'?raw.defaults:{}};}
 function branding(value={},raw={},strict=true){const cap=capabilities(raw),out={};if(!value||typeof value!=='object'||Array.isArray(value))throw Error('Personalizzazione non valida');for(const [key,v] of Object.entries(value)){if(!fields.includes(key)||!cap.fields.includes(key)){if(strict&&v!==''&&v!==null)throw Error('Personalizzazione non supportata: '+key);continue;}if(v===null||v==='')continue;if(typeof v!=='string')throw Error('Valore non valido: '+key);const text=v.trim();if(!text)continue;if(colorKeys.includes(key)){if(!/^#[0-9a-f]{6}$/i.test(text))throw Error('Colore non valido');out[key]=text.toLowerCase();}else if(key==='menu_layout'){if(!cap.menu_layouts.includes(text))throw Error('Menu non supportato');if(text!=='original')out[key]=text;}else if(key.endsWith('_url')){const url=new URL(text);if(url.protocol!=='https:'||url.username||url.password||text.length>2000)throw Error('Immagine non valida: usa HTTPS');out[key]=url.href;}else{if(text.length>(key==='short_name'?30:key==='subtitle'?240:160))throw Error('Testo troppo lungo');out[key]=text;}}return out;}
 function resolve(values,raw){return {...capabilities(raw).defaults,...branding(values||{},raw,false)};}
 function modules(values,definitions,strict=false,defaults=false){const input=values&&typeof values==='object'&&!Array.isArray(values)?values:{},available=definitions.filter(x=>x.ready!==false),allowed=new Set(available.map(x=>x.key||x.id));if(strict&&Object.entries(input).some(([key,on])=>typeof on!=='boolean'||(on&&!allowed.has(key))))throw Error('Modulo non disponibile');const result=Object.fromEntries(available.map(m=>{const key=m.key||m.id;return [key,Object.hasOwn(input,key)?input[key]===true:defaults&&m.default_enabled!==false];}));for(let i=0;i<available.length;i++){let changed=false;for(const m of available){const key=m.key||m.id;if(result[key]&&(m.requires||[]).some(d=>!result[d])){result[key]=false;changed=true;}}if(!changed)break;}return result;}
 globalThis.SimplexTenants=Object.freeze({fields,colorKeys,layouts,presets,luminance,contrast,ink,capabilities,branding,resolve,modules});
})();
