import {provinces,municipalitiesFor,resolveAddress} from '../domain/italian-addresses.js';
export function clientAddressFields(){return `<label class="field">Provincia<select name="province" aria-label="Provincia"></select></label><label class="field">Comune / Città<select name="city" aria-label="Comune / Città"></select></label><label class="field">CAP<span id="client-cap-field"></span><span class="hint" id="client-address-hint"></span></label><input type="hidden" name="municipality_code">`;}
export function bindClientAddress(form,payload={}){
 const province=form.elements.province,city=form.elements.city,code=form.elements.municipality_code,capBox=form.querySelector('#client-cap-field'),hint=form.querySelector('#client-address-hint'),resolved=resolveAddress(payload);
 const option=(value,label)=>{const node=form.ownerDocument.createElement('option');node.value=value;node.textContent=label;return node;},blank=(select,label)=>select.replaceChildren(option('',label));
 blank(province,'Seleziona provincia');for(const p of provinces)province.add(option(p.code,p.name+' ('+p.code+')'));
 if(resolved.province)province.value=resolved.province.code;else if(payload.province){province.add(option(payload.province,payload.province+' · dato esistente'));province.value=payload.province;}
 const caps=(municipality,existing='')=>{code.value=municipality?.[0]||'';capBox.replaceChildren();const values=municipality?.[2]||[];if(values.length){const select=document.createElement('select');select.name='cap';select.setAttribute('aria-label','CAP');if(values.length>1)select.add(option('','Seleziona CAP'));for(const cap of values)select.add(option(cap,cap));if(existing&& !values.includes(existing))select.add(option(existing,existing+' · dato esistente'));select.value=existing|| (values.length===1?values[0]:'');select.required=values.length>1;capBox.append(select);hint.textContent=values.length>1?'Il comune ha più CAP: scegli quello del tuo indirizzo.':'';}else{const input=document.createElement('input');input.name='cap';input.inputMode='numeric';input.maxLength=5;input.pattern='[0-9]{5}';input.value=existing;input.setAttribute('aria-label','CAP');input.readOnly=!city.value;capBox.append(input);hint.textContent=city.value?'CAP non disponibile nell’archivio: verifica il CAP dell’indirizzo.':'Seleziona prima un comune.';}};
 const cities=(initial=false)=>{blank(city,'Seleziona comune');const list=municipalitiesFor(province.value);for(const c of list)city.add(option(c[1],c[1]));city.disabled=!province.value;if(initial&&payload.city){const selected=resolved.city;if(!list.some(c=>c[1]===(selected?.[1]||payload.city)))city.add(option(payload.city,payload.city+' · dato esistente'));city.value=selected?.[1]||payload.city;city.disabled=false;caps(selected,payload.cap||'');}else caps(null);};
 province.onchange=()=>cities();city.onchange=()=>caps(municipalitiesFor(province.value).find(c=>c[1]===city.value));cities(true);
}
